name: dart
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: Alex <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  dartis: ^0.2.0
  #redis_client: ^0.1.16
  #redis: ^0.4.5

#dev_dependencies:
#  test: ^1.0.0
